// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sansunt.MicroService.Demo.Infra.Data.Context;

namespace Sansunt.MicroService.Demo.Infra.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sansunt.MicroService.Demo.Domain.Models.Staff", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("Id")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnName("account")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("create_by")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("create_time");

                    b.Property<int>("DelFlag")
                        .HasColumnName("del_flag");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnName("nick_name")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnName("pwd")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Remark")
                        .HasColumnName("remark")
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnName("update_by")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.HasIndex("Account", "DelFlag", "Id");

                    b.ToTable("sys_staff");
                });
#pragma warning restore 612, 618
        }
    }
}
